services:
  app: 
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - 8080:8000
    environment:
      - MYSQLDB_HOST=192.168.1.71
      - MYSQLDB_DB=db_todo
      - MYSQLDB_USER=todo_user
      - MYSQLDB_PASSWORD=<changeme>
    command: python3 -m flask run --debug --reload --host 0.0.0.0 --port 8000