services:
  app: 
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - 8080:8000
    command: python3 -m flask run --debug --reload --host 0.0.0.0 --port 8000